--- #install java s/w, download tomcat and install.
- hosts: all
  become: yes
  user: ansible
  connection: ssh


  tasks:
    - name: install java on redhat
      yum:
        name: java
        state: installed
      when: ansible_os_family == "RedHat"


    - name: install java on debian
      apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"


    - name: Download tomcat s/w
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.73/bin/apache-tomcat-9.0.73.tar.gz
        dest: /opt


    - name: extract tomcat s/w
      unarchive:
        src: /opt/apache-tomcat-9.0.73.tar.gz
        dest: /opt
        remote_src: yes


    - name: providing executable permissions
      file: 
      path: /opt/apache-tomcat-9.0.73/bin/startup.sh
      mode: 0777


    - name: start tomcat service
      shell: nohup ./startup.sh
      args:
        chdir: /opt/apache-tomcat-9.0.73/bin
