---
- name: test playbook
  hosts: all
  become: yes


  tasks:
    - name: Installin s/w
      yum:
        name: httpd
        state: installed

    - name: start service
      service:
        name: httpd
        state: started
